---
# Installs chocolatey packages.

- name: package installs
  hosts: windows
  gather_facts: false
  tasks:

    - name: Installing GIT.
      win_chocolatey:
	   name: git
	- name: Installing notepad++
      win_chocolatey:
	   name: notepadplusplus.install
