---
# This playbook tests the script module on Windows hosts.

- name: Run powershell script
  hosts: windows
  gather_facts: false
  tasks:
    - name: Run powershell script
      script: D:\git\ansible\files\test_playbook_script.ps1