---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: windows
  gather_facts: false
  tasks:
    - win_command: powershell -c 'ni -it d -path c:\tmp -force; ni -it f -path c:\tmp\test.txt -value "ansible controls me"'
